# Generated by Django 5.0.3 on 2024-04-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.ImageField(blank=True, default='', upload_to='post_images/'),
        ),
    ]
