# Generated by Django 5.0.3 on 2024-04-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_postrank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
